"""add avatar_hash to User model

Revision ID: 15f151e77105
Revises: None
Create Date: 2016-03-05 11:12:18.468485

"""

# revision identifiers, used by Alembic.
revision = '15f151e77105'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'plugins', ['title'])
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    op.drop_constraint(None, 'plugins', type_='unique')
    ### end Alembic commands ###
