"""add plugin model

Revision ID: 3185176165bc
Revises: 36d0d1e4c3c4
Create Date: 2016-03-04 00:05:09.926946

"""

# revision identifiers, used by Alembic.
revision = '3185176165bc'
down_revision = '36d0d1e4c3c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugins')
    ### end Alembic commands ###
