"""add BlogInfo model

Revision ID: 36d0d1e4c3c4
Revises: fd4a80666a6d
Create Date: 2016-03-03 20:56:51.127688

"""

# revision identifiers, used by Alembic.
revision = '36d0d1e4c3c4'
down_revision = 'fd4a80666a6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('navbar', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_info')
    ### end Alembic commands ###
