"""add reply_to to Coment

Revision ID: 54d980b2a0b2
Revises: b58137f24ad6
Create Date: 2016-02-27 21:10:55.804176

"""

# revision identifiers, used by Alembic.
revision = '54d980b2a0b2'
down_revision = 'b58137f24ad6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply_to', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply_to')
    ### end Alembic commands ###
