"""add BlogView model

Revision ID: 648def80874a
Revises: None
Create Date: 2016-03-05 10:32:06.409423

"""

# revision identifiers, used by Alembic.
revision = '648def80874a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_of_view', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'plugins', ['title'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plugins', type_='unique')
    op.drop_table('blog_view')
    ### end Alembic commands ###
