"""rebuild db to add disable comment

Revision ID: ab80ffa457c0
Revises: abf2beac2ffa
Create Date: 2016-02-27 03:03:27.103318

"""

# revision identifiers, used by Alembic.
revision = 'ab80ffa457c0'
down_revision = 'abf2beac2ffa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    ### end Alembic commands ###
