"""add comment_type to Coment

Revision ID: b58137f24ad6
Revises: ab80ffa457c0
Create Date: 2016-02-27 21:01:04.595512

"""

# revision identifiers, used by Alembic.
revision = 'b58137f24ad6'
down_revision = 'ab80ffa457c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_type')
    ### end Alembic commands ###
