"""add Menu model

Revision ID: ca3fda3eaa9d
Revises: 54d980b2a0b2
Create Date: 2016-02-28 22:24:40.979010

"""

# revision identifiers, used by Alembic.
revision = 'ca3fda3eaa9d'
down_revision = '54d980b2a0b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articleTypes', 'menus', ['menu_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articleTypes', type_='foreignkey')
    ### end Alembic commands ###
