"""initial migration

Revision ID: d052e2175d42
Revises: 9b7006db8bda
Create Date: 2016-02-13 18:12:18.095030

"""

# revision identifiers, used by Alembic.
revision = 'd052e2175d42'
down_revision = '9b7006db8bda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'avatar_hash')
    ### end Alembic commands ###
